-- Migration 002: Grant permissions on schema fs to application user fs_app

GRANT USAGE ON SCHEMA fs TO fs_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA fs TO fs_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA fs TO fs_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA fs TO fs_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA fs GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fs_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA fs GRANT USAGE, SELECT ON SEQUENCES TO fs_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA fs GRANT EXECUTE ON FUNCTIONS TO fs_app;

GRANT USAGE ON SCHEMA public TO fs_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO fs_app;
